databases:
  - name: unity-db
    databaseName: unity
    user: unity

services:
  - type: web
    name: unity-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn unity.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: BREVO_TRANSPORT
        value: "api"
      - key: EMAIL_BACKEND
        value: "unity.email_backend.BrevoEmailBackend"
